### ISSUE TITLE
Create a video of the evolving tracks

### ISSUE THREAD

**Issue by MichaelKupferstein** [YCCS-Summer-2023-DDNMA/project#113]
Using matplotlib to create a 2d image and animate them to show the evolving tracks

**Comment by rameshnatarajanus** [comment]
This animation would take as input the emissions/observation sequence y[1...T], the filter_means[1...T] and the filter_covariances[1...T].   As each observation is plotted, it would plot the updates to the positions (that is the first 2 components of the state vector in the corresponding filter means, as well as the ellipsoid that shows the uncertainty (95%) using the corresponding filter_covariances.    This is very similar to the existing plot but it shows how the tracking can be done sequentially, 1 observation at a time.
